name: Build App Bridge

on:
    push:
        branches:
            - master

jobs:
    build-app-bridge:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v2

            - name: Use Node.js 15
              uses: actions/setup-node@v1
              with:
                  node-version: "15"

            - name: Cache NPM dependencies
              id: npm_cache
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install NPM dependencies
              if: steps.npm_cache.outputs.cache-hit != 'true'
              env:
                  CI: 1
              run: npm ci

            - name: Typecheck files
              run: npm run typecheck

            - name: Lint TypeScript files
              run: npm run lint

            - name: Set up git user
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Increase the version
              run: npm version patch

            - name: Build App Bridge
              run: npm run build

            - name: Push the `dist` folder
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: |
                  git add --force -A
                  git commit -m "Released new version"
                  git push --force https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY

            # - name: Publish to npm
            #   run: npm publish
